import { embedMany, generateObject, NoObjectGeneratedError } from 'ai'
import { openai } from '@ai-sdk/openai'

import { parseTranscript, isModerator } from './parse.ts'
import {
  SegmentationSchema,
  SEGMENTATION_SYSTEM_PROMPT,
  formatTurnsForPrompt,
  filterHallucinated,
  type SegmentedUtterance,
} from './segment.ts'
import { aggregateAndProject, isMappable } from './aggregate.ts'
import {
  formatForTranslation,
  needsTranslation,
  TRANSLATION_SYSTEM_PROMPT,
  TranslationsSchema,
} from './translate.ts'
import {
  formatSpeakersForPrompt,
  SPEAKER_NAMES_SYSTEM_PROMPT,
  SpeakerNamesSchema,
  type SpeakerNames,
} from './speakers.ts'
import {
  AXIS_SYSTEM_PROMPT,
  AxisLabelsSchema,
  canLabelAxes,
  formatExtremesForPrompt,
} from './axes.ts'
import {
  canSummarise,
  formatStatementsForPrompt,
  SpeakerSummariesSchema,
  SUMMARY_SYSTEM_PROMPT,
  type SpeakerSummaries,
} from './summaries.ts'
import { EMBEDDING_MODEL, MODEL } from './models.ts'
import type {
  AnalysisResult,
  ProjectionMethod,
  Utterance,
  UtteranceKind,
} from './types.ts'

/**
 * The analysis, from transcript text to a finished map.
 *
 * Lives here rather than in the route handler so that the committed examples
 * are produced by the same code that serves a paste. A fixture generated by a
 * second implementation would drift from the product silently, and the whole
 * claim of the examples is that they are real output rather than pictures drawn
 * in advance.
 */

/** Guards against a paste large enough to blow the function's duration limit. */
export const MAX_TRANSCRIPT_CHARS = 120_000

/**
 * Turns per segmentation call.
 *
 * Kept small deliberately: latency tracks the text volume of the slowest single
 * call, not the number of calls, so many small concurrent batches finish sooner
 * than a few large ones. Measured on a 105-turn transcript: 40 turns/call ran in
 * 73s, 15 turns/call in 28s, for equivalent output.
 */
const SEGMENT_BATCH_TURNS = 15

/**
 * Concurrent segmentation calls. Bounded rather than unlimited so a very long
 * transcript does not open dozens of simultaneous requests and hit provider
 * rate limits, which would fail the whole analysis rather than just slow it.
 */
const SEGMENT_CONCURRENCY = 8

export type AnalysisWithDiagnostics = AnalysisResult & {
  diagnostics: Record<string, unknown>
}

export type AnalyzeOutcome =
  | { ok: true; result: AnalysisWithDiagnostics }
  | { ok: false; status: number; error: string }

export interface AnalyzeOptions {
  /** Include facilitator speech in the map. Off by default. */
  includeModerators?: boolean
}

export async function analyzeTranscript(
  transcript: string,
  { includeModerators = false }: AnalyzeOptions = {},
): Promise<AnalyzeOutcome> {
  if (transcript.length > MAX_TRANSCRIPT_CHARS) {
    return {
      ok: false,
      status: 413,
      error: `Transcript is ${transcript.length} characters; the limit is ${MAX_TRANSCRIPT_CHARS}.`,
    }
  }

  // 1. Attribute lines to speakers.
  const parsed = parseTranscript(transcript)
  if (parsed.turns.length === 0) {
    return {
      ok: false,
      status: 422,
      error:
        'No speaker-attributed lines found. Expected lines like "김철수: ..." or "[김철수] ...".',
    }
  }

  // A map of one person shows no relative position, which is the entire point.
  // Checked here rather than after projection: it used to be caught at the end,
  // which meant a single-speaker transcript paid for segmentation and embedding
  // before being told it could never produce a map.
  const mappableSpeakers = includeModerators
    ? parsed.speakers
    : parsed.speakers.filter((s) => !isModerator(s))
  if (mappableSpeakers.length < 2) {
    return {
      ok: false,
      status: 422,
      error:
        mappableSpeakers.length === 0
          ? 'No speaker could be placed. The transcript may contain only facilitator speech.'
          : 'Only one speaker could be placed. A map needs at least two to show relative position.',
    }
  }

  // Names in the other language, so the toggle reaches the one thing on the map
  // a reader has to be able to read. Runs alongside segmentation rather than
  // after it: it needs only the parsed speaker list, and it is small.
  const speakerNamesPromise = renderSpeakerNames(parsed.speakers)

  // 2. Segment turns into argument units.
  //
  // Batches run concurrently. Sequentially, a real 105-turn transcript took
  // 110s and would have been killed by the 60s function limit. The batches are
  // independent — each needs only its own turns — so wall clock is the slowest
  // call rather than their sum.
  let units: SegmentedUtterance[] = []
  let hallucinatedCount = 0

  const batches: { index: number; turns: { speaker: string; text: string }[] }[] = []
  for (let i = 0; i < parsed.turns.length; i += SEGMENT_BATCH_TURNS) {
    batches.push({
      index: batches.length,
      turns: parsed.turns.slice(i, i + SEGMENT_BATCH_TURNS),
    })
  }

  try {
    const results = await mapWithConcurrency(
      batches,
      SEGMENT_CONCURRENCY,
      async (batch) => {
        const { object } = await generateObject({
          model: openai(MODEL),
          schema: SegmentationSchema,
          system: SEGMENTATION_SYSTEM_PROMPT,
          prompt: formatTurnsForPrompt(batch.turns),
        })
        return { batch, ...filterHallucinated(object.utterances, batch.turns) }
      },
    )

    // Reassemble in batch order so utterance indices follow the transcript.
    results.sort((a, b) => a.batch.index - b.batch.index)
    for (const r of results) {
      units.push(...r.kept)
      hallucinatedCount += r.dropped.length
    }
  } catch (error) {
    // A schema-conformance failure is worth distinguishing from a transport
    // error: it usually means the prompt or schema needs work, not a retry.
    if (NoObjectGeneratedError.isInstance(error)) {
      console.error('segmentation: no object generated', {
        cause: error.cause,
        text: error.text?.slice(0, 500),
      })
      return {
        ok: false,
        status: 502,
        error: 'The model did not return usable segmentation output.',
      }
    }
    const message = error instanceof Error ? error.message : 'Segmentation failed.'
    return { ok: false, status: 502, error: `Segmentation failed: ${message}` }
  }

  if (units.length === 0) {
    return {
      ok: false,
      status: 422,
      error: 'Segmentation produced no usable units. The transcript may be too short.',
    }
  }

  // Reconcile speaker names against the parsed set: the model occasionally
  // returns a variant, and an unrecognised name would create a phantom speaker.
  // Units whose speaker cannot be resolved are dropped, not reassigned.
  const knownSpeakers = new Set(parsed.speakers)
  let unresolvedSpeakerUnits = 0
  units = units.flatMap((u) => {
    if (knownSpeakers.has(u.speaker)) return [u]
    const resolved = nearestSpeaker(u.speaker, parsed.speakers)
    if (resolved) return [{ ...u, speaker: resolved }]
    unresolvedSpeakerUnits += 1
    return []
  })

  if (units.length === 0) {
    return {
      ok: false,
      status: 422,
      error: 'No segmented unit could be attributed to a known speaker.',
    }
  }

  const utterances: Utterance[] = units.map((u, i) => ({
    id: `u${i}`,
    speaker: u.speaker,
    text: u.text,
    // Only carry a translation when it says something the original does not.
    ...(u.textEn && u.textEn.trim() && u.textEn.trim() !== u.text.trim()
      ? { textEn: u.textEn.trim() }
      : {}),
    kind: u.kind,
    index: i,
  }))

  // Fill in translations segmentation left out. See lib/translate.ts: whether a
  // unit needs one is decided by the script it is written in, not by the model.
  const gaps = utterances.filter((u) => needsTranslation(u.text, u.textEn))
  let translationsRepaired = 0
  if (gaps.length > 0) {
    try {
      const { object } = await generateObject({
        model: openai(MODEL),
        schema: TranslationsSchema,
        system: TRANSLATION_SYSTEM_PROMPT,
        prompt: formatForTranslation(gaps.map((u) => u.text)),
      })
      // A short or misaligned array is worse than none: it would attach one
      // statement's translation to another. Only a length match is used.
      if (object.translations.length === gaps.length) {
        gaps.forEach((u, i) => {
          const translated = object.translations[i]?.trim()
          if (translated) {
            u.textEn = translated
            translationsRepaired += 1
          }
        })
      }
    } catch (error) {
      console.error('translation repair failed', error)
    }
  }

  // 3. Embed. Only units that can carry a position need vectors.
  const embeddable = utterances.filter(
    (u) => u.kind === 'claim' || u.kind === 'question',
  )
  if (embeddable.length < 2) {
    return {
      ok: false,
      status: 422,
      error:
        'Fewer than two substantive utterances were found, so no map can be drawn.',
    }
  }

  let vectorByIndex: Map<number, number[]>
  try {
    vectorByIndex = await embedUtterances(embeddable)
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Embedding failed.'
    return { ok: false, status: 502, error: `Embedding failed: ${message}` }
  }

  // 4. Project, once per method, so the client can switch without a round trip.
  const vectors = utterances.map((u) => vectorByIndex.get(u.index) ?? [])
  const excludeSpeakers = includeModerators
    ? []
    : parsed.speakers.filter(isModerator)

  const methods: ProjectionMethod[] = ['people', 'pca', 'mds']
  const projections = {} as AnalysisResult['projections']
  let droppedSpeakers: string[] = []

  for (const method of methods) {
    const out = aggregateAndProject({
      utterances,
      vectors,
      method,
      excludeSpeakers,
    })
    projections[method] = {
      utterances: out.projectedUtterances,
      speakers: out.speakers,
      meta: {
        method,
        explainedVariance: out.explainedVariance,
        componentVariance: out.componentVariance,
        fittedOn: out.fittedOn,
        saturated: out.saturated,
        fitSaturated: out.fitSaturated,
        separation: out.separation,
        attribution: out.attribution,
        secondAxisFromResiduals: out.secondAxisFromResiduals,
        axes: null,
      },
    }
    // Method-independent, so either pass yields the same set.
    droppedSpeakers = out.droppedSpeakers
  }

  // `aggregateAndProject` can only see the speakers that survived segmentation,
  // so somebody whose every unit was dropped upstream — as a hallucination, or
  // for saying nothing but "네, 맞습니다" — disappeared from the map without
  // being reported anywhere. A participant who was in the room and is not in
  // the picture has to be named, or the map quietly claims a meeting had fewer
  // people in it than it did.
  const placedOrDropped = new Set([
    ...projections.pca.speakers.map((s) => s.speaker),
    ...droppedSpeakers,
  ])
  droppedSpeakers = Array.from(
    new Set([
      ...droppedSpeakers,
      ...mappableSpeakers.filter((s) => !placedOrDropped.has(s)),
    ]),
  )

  // A map of one person shows no relative position, which is the entire point.
  // Better to say so than to draw a single marker and let it imply otherwise.
  const placed = projections.pca.speakers.length
  if (placed < 2) {
    return {
      ok: false,
      status: 422,
      error:
        placed === 0
          ? 'No speaker could be placed. The transcript may contain only assent or procedural talk.'
          : 'Only one speaker could be placed. A map needs at least two to show relative position.',
    }
  }

  // 5. Name the two PCA axes from the statements at their ends.
  //
  // Last, and allowed to fail: this is a reading aid, and a map with anonymous
  // axes is the map this tool shipped with for months. Losing the labels to a
  // timeout is not a reason to lose the analysis.
  // Both linear layouts get names: their axes are directions with meaning, and
  // they are different meanings — `people` opens along what separates the
  // participants, `pca` along what the room as a whole differed on. MDS is left
  // alone, since its orientation is arbitrary.
  // 6. Say what each participant argued.
  //
  // Runs beside the axis naming rather than after it, since neither needs the
  // other, and is drawn from the statements rather than from the coordinates —
  // see lib/summaries.ts for why that distinction is the point.
  const placedSpeakers = new Set(
    projections.pca.speakers.map((s) => s.speaker),
  )
  const mappable = utterances.filter(
    (u) => isMappable(u) && placedSpeakers.has(u.speaker),
  )

  const [, speakerSummaries] = await Promise.all([
    Promise.all(
      (['people', 'pca'] as const).map(async (method) => {
        const projection = projections[method]
        if (!canLabelAxes(projection.utterances)) return
        try {
          const { object } = await generateObject({
            model: openai(MODEL),
            schema: AxisLabelsSchema,
            system: AXIS_SYSTEM_PROMPT,
            prompt: formatExtremesForPrompt(projection.utterances),
          })
          projection.meta.axes = object
        } catch (error) {
          console.error(`axis labelling failed for ${method}`, error)
        }
      }),
    ),
    summariseSpeakers(mappable),
  ])

  const speakerNames = await speakerNamesPromise

  const counts: Record<UtteranceKind, number> = {
    claim: 0,
    question: 0,
    agreement: 0,
    procedural: 0,
  }
  for (const u of utterances) counts[u.kind] += 1

  return {
    ok: true,
    result: {
      projections,
      counts,
      droppedSpeakers,
      speakerNames,
      speakerSummaries,
      diagnostics: {
        turns: parsed.turns.length,
        speakers: parsed.speakers,
        moderators: parsed.speakers.filter(isModerator),
        moderatorsExcluded: !includeModerators,
        aliasMap: parsed.aliasMap,
        continuationLines: parsed.continuationLines,
        preambleLines: parsed.preambleLines,
        unitsDroppedAsHallucinated: hallucinatedCount,
        unitsDroppedUnresolvedSpeaker: unresolvedSpeakerUnits,
        translationsRepaired,
        model: MODEL,
        embeddingModel: EMBEDDING_MODEL,
      },
    },
  }
}

/**
 * What each participant argued, keyed by speaker.
 *
 * Never rejects, for the same reason the axis names do not: this is a reading
 * aid over a map that stands without it. A summary lost to a timeout costs a
 * paragraph; a rejected analysis costs the map.
 *
 * Anything the model returns that cannot be checked against the transcript is
 * dropped rather than shown — a summary for a speaker who was not asked about,
 * or anchored to a statement that speaker did not make. The anchors exist so a
 * reader can verify the summary, which they cannot do if the anchors are wrong.
 */
async function summariseSpeakers(
  utterances: Utterance[],
): Promise<SpeakerSummaries | null> {
  if (!canSummarise(utterances)) return null
  try {
    const { object } = await generateObject({
      model: openai(MODEL),
      schema: SpeakerSummariesSchema,
      system: SUMMARY_SYSTEM_PROMPT,
      prompt: formatStatementsForPrompt(utterances),
    })

    const idsBySpeaker = new Map<string, Set<string>>()
    for (const u of utterances) {
      const ids = idsBySpeaker.get(u.speaker)
      if (ids) ids.add(u.id)
      else idsBySpeaker.set(u.speaker, new Set([u.id]))
    }

    const summaries: SpeakerSummaries = {}
    for (const entry of object.summaries) {
      const speaker = entry.speaker.trim()
      const own = idsBySpeaker.get(speaker)
      if (!own || !entry.stance.ko.trim()) continue
      const anchors = entry.anchors.filter((id) => own.has(id))
      summaries[speaker] = { ...entry, speaker, anchors }
    }
    return Object.keys(summaries).length > 0 ? summaries : null
  } catch (error) {
    console.error('speaker summaries failed', error)
    return null
  }
}

/**
 * Each speaker's name written in English.
 *
 * Never rejects: a map with names in one script is the state this shipped in
 * for months, and is a smaller loss than no map at all. Entries the model
 * returns for a name that was not asked about are ignored, so a hallucinated
 * participant cannot appear in the interface.
 */
async function renderSpeakerNames(
  speakers: string[],
): Promise<SpeakerNames | null> {
  if (speakers.length === 0) return null
  try {
    const { object } = await generateObject({
      model: openai(MODEL),
      schema: SpeakerNamesSchema,
      system: SPEAKER_NAMES_SYSTEM_PROMPT,
      prompt: formatSpeakersForPrompt(speakers),
    })
    const asked = new Set(speakers)
    const names: SpeakerNames = {}
    for (const entry of object.names) {
      const source = entry.source.trim()
      const en = entry.en.trim()
      if (asked.has(source) && en) names[source] = en
    }
    return Object.keys(names).length > 0 ? names : null
  } catch (error) {
    console.error('speaker name rendering failed', error)
    return null
  }
}

/**
 * Runs `fn` over `items` with at most `limit` in flight, preserving input order
 * in the returned array. Rejects on the first failure, like Promise.all.
 */
async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  fn: (item: T) => Promise<R>,
): Promise<R[]> {
  const results = new Array<R>(items.length)
  let next = 0

  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (true) {
      const i = next++
      if (i >= items.length) return
      results[i] = await fn(items[i])
    }
  })

  await Promise.all(workers)
  return results
}

/**
 * Embeds utterances, returning vectors keyed by utterance index.
 *
 * `embedMany` chunks against the model's `maxEmbeddingsPerCall` (2048 here),
 * retries, and guarantees the returned array is ordered to match `values`.
 */
async function embedUtterances(
  utterances: Utterance[],
): Promise<Map<number, number[]>> {
  const { embeddings } = await embedMany({
    model: openai.embeddingModel(EMBEDDING_MODEL),
    values: utterances.map((u) => u.text),
    maxParallelCalls: 2,
  })

  const out = new Map<number, number[]>()
  utterances.forEach((u, i) => {
    const vector = embeddings[i]
    if (vector) out.set(u.index, vector)
  })
  return out
}

/**
 * Maps a model-returned speaker name onto a known one, or null if it cannot be
 * resolved confidently.
 *
 * Returns null rather than guessing. Assigning an unresolvable name to the first
 * known speaker would credit real words to the wrong participant and shift that
 * participant's centroid, with nothing in the output to indicate it happened.
 */
export function nearestSpeaker(candidate: string, known: string[]): string | null {
  if (!candidate) return null
  const c = candidate.replace(/\s+/g, '')
  if (!c) return null

  const stripped = known.map((k) => ({ name: k, key: k.replace(/\s+/g, '') }))

  // Exact match after whitespace removal.
  const exact = stripped.find((k) => k.key === c)
  if (exact) return exact.name

  // The candidate carries the known name plus a title, e.g. "김철수 위원".
  const extended = stripped.filter((k) => c.startsWith(k.key))
  if (extended.length === 1) return extended[0].name

  // The candidate is a prefix of exactly one known name. Requiring uniqueness
  // matters for Korean surnames: "김" prefixes both 김철수 and 김영수, and
  // picking the first would attribute by transcript order rather than identity.
  const prefixOf = stripped.filter((k) => k.key.startsWith(c))
  if (prefixOf.length === 1 && c.length >= 2) return prefixOf[0].name

  return null
}
